sudo: false
language: php
php:
    - 7
    - hhvm
before_script:
    - composer self-update
    - composer install --prefer-source
script:
    - chmod -R 777 tests/logs tests/tmp
    - ./vendor/bin/phpunit
after_script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then php vendor/bin/coveralls -v; fi
