<?php


class RouteTest extends \PHPUnit_Framework_TestCase
{
    /** @var \Vu\Router\Route  */
    protected $route;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->route = new \Vu\Router\Route();
    }

    public function testCollectiveRoute()
    {
        $this->route->get('/test', function () {
            return 'test';
        });
        $collection = $this->route->getCollection();
        $this->assertSame('GET', $collection[0][0]);
        $this->assertSame('/test', $collection[0][1]);
    }
}
